name: Prism Auth Service CI

on:
  push:
    branches:
    - main
    - develop
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    # Menentukan service yang dibutuhkan oleh job ini
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: prismuser
          POSTGRES_PASSWORD: prismpassword
          POSTGRES_DB: prism_erp
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
        - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    # Cache dependensi untuk mempercepat build
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Go modules
      run: go mod download

    - name: Run linter
      uses: golangci/golangci-lint-action@v8
      with:
        # Optional: version of golangci-lint to use in form of v1.2.3, defaults to latest if not specified
        version: v2.1

    - name: Run unit tests
      # Menjalankan test yang ditandai sebagai 'short' dan tidak memerlukan dependensi eksternal.
      run: go test -v -short ./...

    - name: Run integration tests
      # FIX: Jalankan script, bukan 'go test' secara langsung.
      # Script ini mengatur env vars yang diperlukan agar TestMain dapat setup DB.
      run: ./scripts/test-integration.sh
      env:
        # Env vars untuk menghubungkan test ke service container di atas
        # Script akan menggunakan ini atau default values.
        POSTGRES_USER: prismuser
        POSTGRES_PASSWORD: prismpassword
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432 # Portnya adalah host port, bukan container port
        REDIS_ADDR: localhost:6379
        JWT_SECRET_KEY: "dummy-secret-for-ci"
        VAULT_ADDR: "http://dummy-vault:8200" # Dummy values
        VAULT_TOKEN: "dummy-token"

    - name: Build the application
      run: go build -v -o ./app ./main.go

    - name: Build Docker image
      # RE-ENABLED: Memastikan Dockerfile valid dan bisa membangun image.
      run: docker build . --file Dockerfile -t lumina-enterprise-solutions/prism-auth-service:${{ github.sha }}
